# Generated by Django 3.0.5 on 2020-05-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('url', models.CharField(max_length=200)),
                ('qrcode', models.ImageField(upload_to='')),
            ],
        ),
    ]
